import {
  Archive,
  BookOpen,
  Bookmark,
  Briefcase,
  Calendar,
  Camera,
  Coffee,
  Code2,
  Dumbbell,
  FileText,
  Folder,
  Globe,
  GraduationCap,
  Heart,
  Home,
  Leaf,
  Lightbulb,
  List,
  ListChecks,
  ListTodo,
  Music,
  NotebookPen,
  PenLine,
  Plane,
  Rocket,
  ShoppingCart,
  Smile,
  Sparkles,
  Star,
  Target,
  Wallet,
  Zap,
  type LucideIcon,
} from "lucide-react";

export type PageIconEntry = { key: string; label: string; Icon: LucideIcon };

export const PAGE_ICONS: PageIconEntry[] = [
  { key: "fileText", label: "Document", Icon: FileText },
  { key: "notebook", label: "Notebook", Icon: NotebookPen },
  { key: "listTodo", label: "To-do list", Icon: ListTodo },
  { key: "listChecks", label: "Checklist", Icon: ListChecks },
  { key: "list", label: "List", Icon: List },
  { key: "sparkles", label: "Sparkles", Icon: Sparkles },
  { key: "star", label: "Star", Icon: Star },
  { key: "heart", label: "Heart", Icon: Heart },
  { key: "bookmark", label: "Bookmark", Icon: Bookmark },
  { key: "book", label: "Book", Icon: BookOpen },
  { key: "lightbulb", label: "Idea", Icon: Lightbulb },
  { key: "calendar", label: "Calendar", Icon: Calendar },
  { key: "target", label: "Goals", Icon: Target },
  { key: "rocket", label: "Rocket", Icon: Rocket },
  { key: "coffee", label: "Coffee", Icon: Coffee },
  { key: "music", label: "Music", Icon: Music },
  { key: "camera", label: "Camera", Icon: Camera },
  { key: "plane", label: "Travel", Icon: Plane },
  { key: "home", label: "Home", Icon: Home },
  { key: "briefcase", label: "Work", Icon: Briefcase },
  { key: "code", label: "Code", Icon: Code2 },
  { key: "study", label: "Study", Icon: GraduationCap },
  { key: "fitness", label: "Fitness", Icon: Dumbbell },
  { key: "shopping", label: "Shopping", Icon: ShoppingCart },
  { key: "wallet", label: "Budget", Icon: Wallet },
  { key: "pen", label: "Writing", Icon: PenLine },
  { key: "folder", label: "Folder", Icon: Folder },
  { key: "archive", label: "Archive", Icon: Archive },
  { key: "zap", label: "Energy", Icon: Zap },
  { key: "leaf", label: "Nature", Icon: Leaf },
  { key: "globe", label: "World", Icon: Globe },
  { key: "smile", label: "Fun", Icon: Smile },
];

const ICON_MAP = new Map(PAGE_ICONS.map((entry) => [entry.key, entry.Icon]));

export function getPageIcon(key: string | null | undefined): LucideIcon {
  if (!key) return FileText;
  return ICON_MAP.get(key) ?? FileText;
}
